name: First Workflow # Nombre del Workflow

on: 
  workflow_dispatch: # Evento para disparar el workflow de forma manual

jobs: # Lista de jobs en el workflow
  first-job: # ID/nombre del primer job
    runs-on: ubuntu-latest # aprovisionamiento de la máquina virtual
    steps: # pasos de este job
      - name: Print greeting # Nombre del primer paso
        run: echo "Hello World!" # comando a ejecutar

      - name: Print goodbye # Nombre del segundo paso
        run: echo "Done - bye!" # comando a ejecutar


